name:                jane
version:             0.1.0.0
github:              "willianszwy/jane"
license:             MIT
author:              "Willians Amaral de Oliveira"
maintainer:          "willianszwy@gmail.com"
copyright:           "2018 Willians Oliveira"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/willianszwy/jane#readme>

dependencies:
- base >= 4.7 && < 5
- binary-strict
- bytestring
- ncurses
- mtl
- containers
- vector

library:
  source-dirs: src

executables:
  jane-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jane
    

tests:
  jane-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jane
    - hspec
    - QuickCheck
